# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: dschep/install-pipenv-action@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install chardet dependency
      run: |
        pip3 install chardet pytest requests semver scikit-image boto3 natsort
    - name: Install dependencies
      run: |
        pipenv install --dev --system
    - name: Unit test with pytest
      env:
        SPB_ACCESS_KEY: ${{ secrets.SPB_ACCESS_KEY }}
        SPB_TEAM_NAME: ${{ secrets.SPB_TEAM_NAME }}
        SPB_APP_API_ENDPOINT: https://api.dev.superb-ai.com/v2/graphql
      run: |
        python -m pytest ./tests

