# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop, master ]

jobs:
  unit_test_python37:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: install packages
      run: |
        pip3 install pytest
    - name: SPB-CLI Install
      run: |
        python setup.py install
    - name: Version Check
      run: |
        python -m spb --version
        python -m spb describe projects
    - name: Unit test with pytest
      env:
        SPB_ACCESS_KEY: ${{ secrets.SPB_ACCESS_KEY }}
        SPB_TEAM_NAME: ${{ secrets.SPB_ACCOUNT_NAME }}
        SPB_APP_API_ENDPOINT: https://api.dev.superb-ai.com
      run: |
        python -m pytest ./tests

  unit_test_python38:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: install packages
      run: |
        pip3 install pytest
    - name: SPB-CLI Install
      run: |
        python setup.py install
    - name: Version Check
      run: |
        python -m spb --version
        python -m spb describe projects
    - name: Unit test with pytest
      env:
        SPB_ACCESS_KEY: ${{ secrets.SPB_ACCESS_KEY }}
        SPB_TEAM_NAME: ${{ secrets.SPB_ACCOUNT_NAME }}
        SPB_APP_API_ENDPOINT: https://api.dev.superb-ai.com
      run: |
        python -m pytest ./tests

  unit_test_python39:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: install packages
      run: |
        pip3 install pytest
    - name: SPB-CLI Install
      run: |
        python setup.py install
    - name: Version Check
      run: |
        python -m spb --version
        python -m spb describe projects
    - name: Unit test with pytest
      env:
        SPB_ACCESS_KEY: ${{ secrets.SPB_ACCESS_KEY }}
        SPB_TEAM_NAME: ${{ secrets.SPB_ACCOUNT_NAME }}
        SPB_APP_API_ENDPOINT: https://api.dev.superb-ai.com
      run: |
        python -m pytest ./tests
